plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme

# Add custom head include
head_scripts:
  - head-custom.html

sass:
  style: compressed

# Add custom stylesheet
styles:
  - /assets/css/custom.css
